[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "Automata"
version = "0.1.0"
description = "A brief description of my package."
authors = ["Kyryl R <kyryl.ryabov@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "lab1" },
]

[tool.poetry.scripts]
black = "black:main"
example = "lab1.examples.example:main"

[tool.poetry.dependencies]
python = "^3.11"
automata-lib = {extras = ["visual"], version = "^8.1.0"}

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
pytest = "^7.4.2"
black = "^23.9.1"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
  | foo.py           # also separately exclude a file named foo.py
                      # at the root of the project
)
'''

[tool.pytest.ini-options]
minversion = "6.0"
addopts = "--cov=lab1 --cov-report=html"
testpaths = [
    "tests",
]

